#!/usr/bin/env bash
# setup loadbalancer with HAProxy
apt-get update
apt-get upgrade -y
apt-get install haproxy -y
echo "ENABLED=1" >> /etc/default/haproxy
echo -e "
frontend load_balancer
	bind :80
	use_backend web_servers

backend web_servers
	balance roundrobin
	server web-01 54.210.126.177:80
	server web-02 18.208.120.189:80" >> /etc/haproxy/haproxy.cfg

service haproxy start
