#!/usr/bin/env bash
# backup all MySQL databases in a tar.gz archive
archive_name=$(date -u +'%d-%m-%Y')
mysqldump -uroot -p"$1" --all-databases > backup.sql && tar -czf "$archive_name".tar.gz backup.sql
