#!/usr/bin/env bash
#Block the fkin facebook from your lovely machine, and change the localhost ip
echo -e '127.0.0.2\tlocalhost\n8.8.8.8\t\tfacebook.com' > ./hosts
grep --invert-match 'localhost\|facebook.com' /etc/hosts >> ./hosts
cp -f ./hosts /etc/hosts
